title: Mukul Sauhta
logo: /assets/img/headshot.png
description: "Software & Data Engineering Portfolio"
#show_downloads: true
theme: jekyll-theme-minimal
include:
  - assets/css/custom.css

# Additional settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Social links
github_username: muksaw
linkedin_username: mukul-sauhta-4b4276234

